### ISSUE TITLE
Update Marvel Characters

### ISSUE THREAD

**Issue by jessicablank** [jessicablank/marvel-match#6]
We discovered the API is not a comprehensive database of Marvel Characters and the characters must be perfectly phrased. Confirm spelling and characters in 6/24's stand-up meeting:
Current: 
Black Panther
Iron Man
Captain Marvel
The Hulk
Thor

Proposed:
Captain America
Iron Man
Spider-Man
The Hulk
Thor

**Comment by tober65** [comment]
Updated characters to ones in the database.
